apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: zou84rkw7-java-quarkus
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/rhtap-qe-java-quarkus:270716f6494062a4a644bb3b4bb4f039d6e37e2f@sha256:1805e13b51a394fe140d2e67be7e2ad9c5baf86f2f90f8e7af7c08d3e40c9f52
          name: container-image
